
//////////////////////////////////////////////////////////////////////
// FindLock() -- find the appropriate lock given a name
// CLASS:    CLock
// AUTHOR:    Dewey M. Sasser
// VISIBILITY:    PROTECTED
// SYNOPSIS
// DESCRIPTION
//   This function returns the lock object associated with csName.
//   This lock object may be used to voluntarily serialize access any
//   shared resource that can be named with a string.  The lock does
//   not have to be destroyed after use.  That will be taken care of
//   automatically. 
// ARGUMENTS
//   csName (const CString &) -- name of the lock to find.
// RETURNS
//   (CLock *) -- the associated lock
// EXCEPTIONS:    NONE
// NOTES
//   |><|
// SEE ALSO
//   |><|
// CAVEATS AND BUGS
//   |><|
//   
//   
XXXPOINTXXX
CLock *CLock::FindLock(const CString &csName)
{
