//////////////////////////////////////////////////////////////////////
// AddNode() -- Add a node to the list box
// CLASS:    CHierListBox
// AUTHOR:    Ken Cherenichenko
// VISIBILITY:    PROTECTED
XXXPOINTXXX// SYNOPSIS
//   
//   BOOL CHierListBox::AddNode (SHORT sTypeOffset, INT nIndex /*LB_ERR-5*/, BOOL fFind/*FALSE*/)
//   
// DESCRIPTION
//   |>Description of function<|
// ARGUMENTS
//   sTypeOffset (SHORT) --
//   nIndex (INT) -- index of where to add the node
//   fFind ( BOOL) --
// RETURNS
//   (BOOL) -- 
//          TRUE - success
//          FALSE - invalid index
// EXCEPTIONS:    NONE
// NOTES
//   |><|
// SEE ALSO
//   |><|
// CAVEATS AND BUGS
//   |><|

BOOL CHierListBox::AddNode (SHORT sTypeOffset, INT nIndex /*LB_ERR-5*/,
			    BOOL fFind/*FALSE*/)
{
